services:
  web:
    build:
      context: .
    container_name: event_driven_backend
    ports:
      - "5018:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1G
